version: '3.1'

services:

  workout_db:
    image: postgres
    restart: "no"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: workout_db
    volumes: 
      - ~/.SQLDBData/postgre/teste:/var/lib/postgresql/data/
    ports:
      - 5432:5432