"""add migration to TransactionTypeEnum and type column in transaction table

Revision ID: 0c57f6693e56
Revises: 590b96eb849a
Create Date: 2026-04-27 09:01:15.994624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c57f6693e56'
down_revision: Union[str, Sequence[str], None] = '590b96eb849a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DEPOSIT', 'WITHDRAWAL', name='transaction_type_enum').create(op.get_bind())
    op.add_column('transactions', sa.Column('type', postgresql.ENUM('DEPOSIT', 'WITHDRAWAL', name='transaction_type_enum', create_type=False), nullable=False))
    op.create_unique_constraint(None, 'transactions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'type')
    sa.Enum('DEPOSIT', 'WITHDRAWAL', name='transaction_type_enum').drop(op.get_bind())
    # ### end Alembic commands ###
