"""fix status enum name and add arg create type

Revision ID: 21330e9410f9
Revises: 0c57f6693e56
Create Date: 2026-04-27 09:07:49.116808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21330e9410f9'
down_revision: Union[str, Sequence[str], None] = '0c57f6693e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NO_RESOURSES', 'REFUND', 'ACCEPT', name='transaction_status_enum').create(op.get_bind())
    op.alter_column('transactions', 'status',
               existing_type=postgresql.ENUM('NO_RESOURSES', 'REFUND', 'ACCEPT', name='transaciont_status_enum'),
               type_=sa.Enum('NO_RESOURSES', 'REFUND', 'ACCEPT', name='transaction_status_enum'),
               existing_nullable=False,
               postgresql_using='status::text::transaction_status_enum')
    sa.Enum('NO_RESOURSES', 'REFUND', 'ACCEPT', name='transaciont_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NO_RESOURSES', 'REFUND', 'ACCEPT', name='transaciont_status_enum').create(op.get_bind())
    op.alter_column('transactions', 'status',
               existing_type=sa.Enum('NO_RESOURSES', 'REFUND', 'ACCEPT', name='transaction_status_enum'),
               type_=postgresql.ENUM('NO_RESOURSES', 'REFUND', 'ACCEPT', name='transaciont_status_enum'),
               existing_nullable=False)
    sa.Enum('NO_RESOURSES', 'REFUND', 'ACCEPT', name='transaction_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
