"""add password and role column in AccountModel

Revision ID: 47e3511d327c
Revises: 41af4d666ce6
Create Date: 2026-04-12 09:57:13.916436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e3511d327c'
down_revision: Union[str, Sequence[str], None] = '41af4d666ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

role_enum = sa.Enum(
    "CUSTOMER", "ADMIN", name="role_enum"
)


def upgrade() -> None:
    """Upgrade schema."""
    role_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('password', sa.VARCHAR(length=60), nullable=False))
    op.add_column('accounts', sa.Column('role', sa.Enum('CUSTOMER', 'ADMIN', name='role_enum'), nullable=False))
    op.create_unique_constraint(None, 'accounts', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("accounts", "role")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_column('accounts', 'role')
    op.drop_column('accounts', 'password')
    # ### end Alembic commands ###
