"""add native support to enums from alembic-postgresql-enum

Revision ID: 590b96eb849a
Revises: cc91124fd8d2
Create Date: 2026-04-25 18:59:37.576709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590b96eb849a'
down_revision: Union[str, Sequence[str], None] = 'cc91124fd8d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('amount', sa.BIGINT(), nullable=False),
    sa.Column('balance_after', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.Enum('NO_RESOURSES', 'REFUND', 'ACCEPT', name='transaciont_status_enum'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
