"""add migration to TransactionTypeEnum and type column in transaction table

Revision ID: 66e324a9326b
Revises: 590b96eb849a
Create Date: 2026-04-27 08:45:22.915208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e324a9326b'
down_revision: Union[str, Sequence[str], None] = '590b96eb849a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', name='transaction_type_enum'), nullable=False))
    op.create_unique_constraint(None, 'transactions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'type')
    # ### end Alembic commands ###
