version: "3.9"

services:
  mongo:
    image: mongo
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: passwd
      MONGO_INITDB_DATABASE: store
    ports:
      - 27017:27017
