version: '3.1'

services:

  book_store:
    image: postgres:11-alpine
    restart: "no"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: book_store
    networks:
      - book_store_backend
    ports:
      - 5432:5432

  book_api_1:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - book_store_backend
    volumes:
      - ./:/app
    expose:
      - 8000

  book_api_2:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - book_store_backend
    volumes:
      - ./:/app
    expose:
      - 8000

  book_api_3:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - book_store_backend
    volumes:
      - ./:/app
    expose:
      - 8000

  nginx:
    image: nginx:alpine
    depends_on:
      - book_api_1
      - book_api_2
      - book_api_3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - book_store_backend

networks:
  book_store_backend:
